### ISSUE TITLE
issue in training with latest commit 

### ISSUE THREAD

**Issue by rohithkodali** [facebookresearch/wav2letter#185]
I have updated the code to latest commit https://github.com/facebookresearch/wav2letter/commit/7406a98bb284aba6f0fcdf1cf449df699644199a which was 2 hours before i'm getting an exception in arrayfire while training for timit 

FYI: i'm using docker-cuda for experimentation

wav2letter/recipes/timit/configs/conv_relu$ sudo docker run  -it wav2letter /root/wav2letter/build/Train train  train.cfg
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function cuda::DeviceManager::DeviceManager()
In file src/backend/cuda/platform.cpp:509
CUDA Error (35): CUDA driver version is insufficient for CUDA runtime version

In function void af::setMemStepSize(size_t)
In file src/api/cpp/device.cpp:179
*** Aborted at 1548817022 (unix time) try "date -d @1548817022" if you are using GNU date ***
PC: @     0x7ff15c445428 gsignal
*** SIGABRT (@0x1) received by PID 1 (TID 0x7ff1b8b69780) from PID 1; stack trace: ***
    @     0x7ff1b1ab0390 (unknown)
    @     0x7ff15c445428 gsignal
    @     0x7ff15c44702a abort
    @     0x7ff15cd8884d __gnu_cxx::__verbose_terminate_handler()
    @     0x7ff15cd866b6 (unknown)
    @     0x7ff15cd86701 std::terminate()
    @     0x7ff15cd86919 __cxa_throw
    @     0x7ff15d6026a1 af::setMemStepSize()
    @           0x41784e main
    @     0x7ff15c430830 __libc_start_main
    @           0x45b8c9 _start
    @                0x0 (unknown)

**Comment by jacobkahn** [comment]
https://github.com/facebookresearch/wav2letter/issues/123. Update your CUDA driver.

**Comment by mrjj** [comment]
@jacobkahn thank you!
Confirming, CUDA update seems to be proper treatment

I thought i had latest driver and cuda being installed via nvidia `*.run` distributions.
It worked fine in single-GPU mode but i suppose that NVIDIA-mpi got to be sensitive to minor version difference between one going stand-alone and in CUDA distro bundle.

Problem gone away after installing `nvidia-driver-cuda` package and it deps tree from repo introduced by [cuda-repo](https://rpmfusion.org/Howto/CUDA) package without pinned driver version.

```sh
$ sudo yum install -y https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-repo-rhel7-10.1.105-1.x86_64.rpm
$ sudo yum install -y nvidia-driver-cuda.x86_64
```

Here is final snapshot of working host with 4 GPU nodes:

```
$ docker -v ; nvidia-container-runtime -v ; cat /etc/redhat-release ; rpm -qf /etc/redhat-release ; yum list installed | grep nvidia ; nvidia-smi
Docker version 18.09.3, build 774a1f4
runc version 1.0.0-rc6+dev
commit: 12f6a991201fdb8f82579582d5e00e28fba06d0a-dirty
spec: 1.0.1-dev
CentOS Linux release 7.6.1810 (Core)
centos-release-7-6.1810.2.el7.centos.x86_64
dkms-nvidia.x86_64                   3:418.39-1.el7                 @cuda-10-1-local-10.1.105-418.39
libnvidia-container-tools.x86_64     1.0.1-1                        @libnvidia-container
libnvidia-container1.x86_64          1.0.1-1                        @libnvidia-container
nvidia-container-runtime.x86_64      2.0.0-1.docker18.09.3          @nvidia-container-runtime
nvidia-container-runtime-hook.x86_64 1.4.0-2                        @nvidia-container-runtime
nvidia-docker2.noarch                2.0.3-1.docker18.09.3.ce       @nvidia-docker
nvidia-driver.x86_64                 3:418.39-4.el7                 @cuda-10-1-local-10.1.105-418.39
nvidia-driver-NVML.x86_64            3:418.39-4.el7                 @cuda-10-1-local-10.1.105-418.39
nvidia-driver-cuda.x86_64            3:418.39-4.el7                 @cuda-10-1-local-10.1.105-418.39
nvidia-driver-cuda-libs.x86_64       3:418.39-4.el7                 @cuda-10-1-local-10.1.105-418.39
nvidia-driver-libs.x86_64            3:418.39-4.el7                 @cuda-10-1-local-10.1.105-418.39
nvidia-persistenced.x86_64           3:418.39-1.el7                 @cuda-10-1-local-10.1.105-418.39
Fri Mar  8 03:40:46 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.43       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:04:00.0 Off |                  N/A |
| 36%   80C    P2   241W / 250W |  10778MiB / 12212MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:08:00.0 Off |                  N/A |
| 38%   82C    P2   238W / 250W |  10674MiB / 12212MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 00000000:84:00.0 Off |                  N/A |
| 38%   82C    P2   240W / 250W |  10598MiB / 12212MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 00000000:88:00.0 Off |                  N/A |
| 38%   82C    P2   256W / 250W |  10674MiB / 12212MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      4264      C   /root/wav2letter/build/Train               10767MiB |
|    1      4263      C   /root/wav2letter/build/Train               10663MiB |
|    2      4262      C   /root/wav2letter/build/Train               10587MiB |
|    3      4261      C   /root/wav2letter/build/Train               10663MiB |
+-----------------------------------------------------------------------------+
```

Runner:

```
#!/usr/bin/env bash

export GPU_UNITS=${GPU_UNITS:-4}
export RUNTIME="--runtime=nvidia"

echo "Running training in MPI distributed mode on ${GPU_UNITS} GPU units"

docker run \
    ${RUNTIME} \
    -v $(pwd)/DATA/:/DATA/ \
    -v $(pwd)/olap/wav2letter/config/LibriSpeech/:/CONFIG/ \
    -t vanilla/wav2letter:cuda-dd45f55fb8a1d32c85303a53121d674207becbba \
    sh -c "cd /DATA/models && mpirun --allow-run-as-root -n ${GPU_UNITS} /root/wav2letter/build/Train train -enable_distributed true --flagsfile /CONFIG/train.cfg"
```
