### ISSUE TITLE
wav2vec and wav2letter out of memory on V100 16GB

### ISSUE THREAD

**Issue by maltium** [facebookresearch/wav2letter#436]
I've bumped into the wav2vec paper (https://arxiv.org/pdf/1904.05862.pdf) and I thought I'd give it a go. After I trained wav2vec and generated the embeddings for my dataset I ended with a bunch of hdf5 files.

Although the wav2vec_featurize.py file seems to suggest that wav2letter can load hdf5 files, this is clearly not the case. So I wrote my own hdf5 loader and made sure all the featurizations in wav2letter are turned off.

My issue is that as soon as I start the training (batch size of 1) on a Tesla V100 16GB, I run into a CUDA out of memory error. I am aware that the features produced by wav2vec contain significantly more data than the usual mfcc features, since they produce 512 features for every 10ms of audio. My longest clips are 30sec.

Maybe they are using a modified network.arch file (I'm using an unmodified WSJ arch)? Or a V100 32GB? Possibly training on very short utterances (TIMIT and WSJ)?

Suggestions are greatly appreciated as I'm pretty much stumped.

**Comment by maltium** [comment]
Turned out the implementation was incomplete. This issue can be closed.

**Comment by nmfisher** [comment]
@maltium Curious to know what your results were like with wav2vec + wav2letter?

**Comment by maltium** [comment]
@nmfisher Unfortunately I haven't got any results to show yet. As the chart below illustrates, I'm running into overfitting issues. I'm now experimenting with increasing the dropout.

![image](https://user-images.githubusercontent.com/4674453/68807772-b4542400-0668-11ea-9770-84d41bda3702.png)

One thing I've noticed is that training is much faster using the wav2vec embeddings compared to MFCC features. Also, previously I was using the WSJ receipe (I have around 40 hours of data) but I've found that I have to reduce the learning rate significantly for the network to learn the wav2vec embeddings.

The wav2vec paper does not specifically mention that any hyperparameter/architecture adjustments were made compared to training with MFCC features, so there is the possibility that my implementation is somewhat bugged. Unfortunately I don't have access to the WSJ dataset, so I can't try to replicate their results.

**Comment by pkumarsatish** [comment]
@maltium I would really appreciate if you can please share the code changes in wav2letter++ to incorporate the hdf5 feature files directly.

**Comment by maltium** [comment]
> @maltium I would really appreciate if you can please share the code changes in wav2letter++ to incorporate the hdf5 feature files directly.

Code is in this feature branch https://github.com/maltium/wav2letter/tree/feature/loading-from-hdf5. Just specify -wav2vec=true instead of whatever features you're extracting. If you have any fixes/improvements please let me know.

**Comment by alpoktem** [comment]
Hi, great to see someone already develop for wav2vec integration. I've been trying to build with @maltium's loading-from-hdf5 feature. I am getting an error while building. I'd appreciate any kind of help. 

I build using the same instructions of wav2letter on Ubuntu and with GPU:
```
mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j4
```

Here's the error I get while building: https://gist.github.com/alpoktem/07a6bbc1e6aba4009d801a04f3c24ca0

It seems like there was a version change with flashlight. Which version is this branch using?
Thanks

**Comment by maltium** [comment]
@alpoktem that's a gcc issue that was fixed on master a few days ago 4289710cd65f03722d6d0d20d801e82290823408. You'll have to merge master from to get the fix.

Also make sure you have the hdf5 dev files installed (_libhdf5-dev_ on debian systems).

**Comment by alpoktem** [comment]
Alright solved the installation issue! Thanks @maltium.

I did the Librispeech tutorial with wav2vec embeddings and got 10.63% WER on the test set. (Without the pre-training it gives 18.67%)

**Comment by BoneGoat** [comment]
I trained a wav2letter model with wav2vec embeddings and stopped at 15% WER. Decoding with the model produces empty transcription. Can I use wavs as input when decoding or do I have to convert to hdf5?

**Comment by WernerDreier** [comment]
> The wav2vec paper does not specifically mention that any hyperparameter/architecture adjustments were made compared to training with MFCC features, so there is the possibility that my implementation is somewhat bugged. Unfortunately I don't have access to the WSJ dataset, so I can't try to replicate their results.

@maltium just started research on wav2vec. I try to adopt wav2vec to be used with deepspeech2 model. First run seems to show similiar behaviour as you describe: Training is much faster compared to same inputdata encoded as spectrogram. However overfitting seems to be a problem. Therefore I will try to increase dropout and/or lower learning-rate. 

Have you found any settings working for you?

**Comment by maltium** [comment]
> Have you found any settings working for you?

What I found out is that even without wav2vec, I was getting overfitting, so wav2vec wasn't the culprit in my case. Wav2vec was simply overfitting more quickly because training was significantly faster. The problem was I had to little data (35hrs) and the expectations with that amount of data have to be set accordingly.

So even though wav2vec marginally improved the performance (compared to baseline), I would say you probably need more data or a different approach altogether.

**Comment by WernerDreier** [comment]
> 
> 
> > Have you found any settings working for you?
> 
> What I found out is that even without wav2vec, I was getting overfitting, so wav2vec wasn't the culprit in my case. Wav2vec was simply overfitting more quickly because training was significantly faster. The problem was I had to little data (35hrs) and the expectations with that amount of data have to be set accordingly.
> 
> So even though wav2vec marginally improved the performance (compared to baseline), I would say you probably need more data or a different approach altogether.

@maltium  Thank you for sharing your insights. My setup includes > 400hrs untranscribed data for wav2vec, but also only ~45hrs of transcribed data for the actual ASR. Could be a similiar case as yours. If I find anything useful, I'd be happy to share my findings.

**Comment by maltium** [comment]
@WernerDreier yes I believe you're running in the same issue I had. In the end I got a WER of around 30%.

**Comment by AlonsoDiCandia** [comment]
> Alright solved the installation issue! Thanks @maltium.
> 
> I did the Librispeech tutorial with wav2vec embeddings and got 10.63% WER on the test set. (Without the pre-training it gives 18.67%)

Where do you pass the hdf5 to wav2letter ? I dont understand how do I pass the h5 files from wav2vec to wav2letter...

**Comment by maltium** [comment]
> Hi everyone, i had some question, where do you pass the hdf5 to wav2letter ? I dont understand how do I pass the h5 files from wav2vec to wav2letter...

Instead of flac filepaths, pass the hdf5 filepaths.

**Comment by aadil-srivastava01** [comment]
> > Hi everyone, I had some question, where do you pass the hdf5 to wav2letter? I don't understand how do I pass the h5 files from wav2vec to wav2letter...
> 
> Instead of flac file paths, pass the hdf5 file paths.

Hi @maltium,  
Thanks for creating this awesome feature, but if you won't mind can you share a bit of snippet on how to start the training, I've been trying for a long time I have the hdf5 files but I'm constantly failing to start the training process.
Thanks

**Comment by aadil-srivastava01** [comment]
> > The wav2vec paper does not specifically mention that any hyperparameter/architecture adjustments were made compared to training with MFCC features, so there is the possibility that my implementation is somewhat bugged. Unfortunately I don't have access to the WSJ dataset, so I can't try to replicate their results.
> 
> @maltium just started research on wav2vec. I try to adopt wav2vec to be used with deepspeech2 model. First run seems to show similiar behaviour as you describe: Training is much faster compared to same inputdata encoded as spectrogram. However overfitting seems to be a problem. Therefore I will try to increase dropout and/or lower learning-rate.
> 
> Have you found any settings working for you?

Hi 


> > The wav2vec paper does not specifically mention that any hyperparameter/architecture adjustments were made compared to training with MFCC features, so there is the possibility that my implementation is somewhat bugged. Unfortunately I don't have access to the WSJ dataset, so I can't try to replicate their results.
> 
> @maltium just started research on wav2vec. I try to adopt wav2vec to be used with deepspeech2 model. First run seems to show similiar behaviour as you describe: Training is much faster compared to same inputdata encoded as spectrogram. However overfitting seems to be a problem. Therefore I will try to increase dropout and/or lower learning-rate.
> 
> Have you found any settings working for you?

Hi @WernerDreier,

Can you can to share a few details on how you fed the output for wave2vec to deep speech 2?

**Comment by rajeevbaalwan** [comment]
@maltium 
with all dependencies installed i am able to successfully build wav2letter but when 
I tried to build wav2letter from feature/loading-from-hdf5 branch but getting this error:

/home/maltinum/wav2letter/src/criterion/Seq2SeqCriterion.cpp: In constructor 'w2l::Seq2SeqCriterion::Seq2SeqCriterion(int, int, int, int, const std::vector<std::shared_ptr<w2l::AttentionBase> >&, std::shared_ptr<w2l::WindowBase>, bool, int, double, bool, std::__cxx11::string, double, int, int, float)':
/home/maltinum/wav2letter/src/criterion/Seq2SeqCriterion.cpp:198:61: error: call of overloaded 'uniform(af::dim4, double, double)' is ambiguous
   params_.push_back(uniform(af::dim4{hiddenDim}, -1e-1, 1e-1));
                                                             ^
In file included from /usr/local/include/flashlight/nn/nn.h:20:0,
                 from /usr/local/include/flashlight/flashlight.h:17,
                 from /home/maltinum/wav2letter/src/criterion/SequenceCriterion.h:11,
                 from /home/maltinum/wav2letter/src/criterion/Seq2SeqCriterion.h:13,
                 from /home/maltinum/wav2letter/src/criterion/Seq2SeqCriterion.cpp:9:
/usr/local/include/flashlight/nn/Init.h:287:10: note: candidate: fl::Variable fl::uniform(af::dim4, double, double, af::dtype, bool)
 Variable uniform(
          ^
/usr/local/include/flashlight/nn/Init.h:46:11: note: candidate: af::array af::uniform(af::dim4, double, double, af::dtype)
 af::array uniform(
           ^
[  7%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/attention/MedianWindow.cpp.o
[  7%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/attention/SoftPretrainWindow.cpp.o
[  7%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/attention/SoftWindow.cpp.o
CMakeFiles/wav2letter++.dir/build.make:998: recipe for target 'CMakeFiles/wav2letter++.dir/src/criterion/Seq2SeqCriterion.cpp.o' failed
make[2]: *** [CMakeFiles/wav2letter++.dir/src/criterion/Seq2SeqCriterion.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:189: recipe for target 'CMakeFiles/wav2letter++.dir/all' failed
make[1]: *** [CMakeFiles/wav2letter++.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Please help me out in this.

**Comment by doanthuan** [comment]
Hi @rajeevbaalwan ,

I had the same issue. Did you figure out how to solve it? Thanks

**Comment by rajeevbaalwan** [comment]
Hi @maltium 
I am able to build wav2letter successfully but getting problem while reading hdf5 files.
I have generated my hdf5 file using standard code provided in fairseq repo which generates .h5context files which i renamed to .h5 before feeding to wav2letter.
I have specified --wav2vec=true as you suggested but then i am getting this error

I0708 16:20:48.048377 26721 Train.cpp:516] Shuffling trainset
I0708 16:20:48.050161 26721 Train.cpp:523] Epoch 1 started!
terminate called after throwing an instance of 'H5::FileIException'
*** Aborted at 1594225248 (unix time) try "date -d @1594225248" if you are using GNU date ***
PC: @     0x7f9ed4968e97 gsignal
*** SIGABRT (@0x6861) received by PID 26721 (TID 0x7f9f1a9f3380) from PID 26721; stack trace: ***
    @     0x7f9f12d0b890 (unknown)
    @     0x7f9ed4968e97 gsignal
    @     0x7f9ed496a801 abort
    @     0x7f9ed535d957 (unknown)
    @     0x7f9ed5363ab6 (unknown)
    @     0x7f9ed5363af1 std::terminate()
    @     0x7f9ed5363d24 __cxa_throw
    @     0x7f9ed5bff3b4 H5::H5File::H5File()
    @     0x55d4aca08514 loadData()
    @     0x55d4aca253d8 w2l::W2lListFilesDataset::getLoaderData()
    @     0x55d4aca13ff7 w2l::W2lDataset::getFeatureData()
    @     0x55d4aca157a6 w2l::W2lDataset::getFeatureDataAndPrefetch()
    @     0x55d4aca15d0e w2l::W2lDataset::get()
    @     0x55d4ac859567 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddbiE3_clES2_S5_S7_S9_S9_ddbi
    @     0x55d4ac7f5c4e main
    @     0x7f9ed494bb97 __libc_start_main
    @     0x55d4ac8540aa _start
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node c06295e75745 exited on signal 6 (Aborted).

What is going on in here is there any issue with hdf5 files. do i need to generate .h5 files instead .h5context from fairseq again ?

**Comment by maltium** [comment]
@rajeevbaalwan I don't recall seeing any h5context files. As a test to check the validity of your hdf5 files, try to load them with the official [HDF View](https://www.hdfgroup.org/downloads/hdfview/) application. Also keep in mind changes in fairseq might have altered the data structures inside the hdf5 file, so in that case you'd have to implement the changes.

**Comment by rajeevbaalwan** [comment]
@maltium thanks, i have been able to run the training with wav2vec but 001_perf, 001_config, 001_log, and model_checpoints are not being saved in directory specified by flag --archdir and --runname.

Also to decide epoch to run training i have been using --iter flag while training with official wav2letter repo but it is not working here. I have passed iter flag for 100 epoch but training was keep on going even after 100 epoch.

Is this code way behind original repo ? do i need to merge feature/loading-from-hdf5 into master ?

**Comment by rajeevbaalwan** [comment]
> @rajeevbaalwan I don't recall seeing any h5context files. As a test to check the validity of your hdf5 files, try to load them with the official [HDF View](https://www.hdfgroup.org/downloads/hdfview/) application. Also keep in mind changes in fairseq might have altered the data structures inside the hdf5 file, so in that case you'd have to implement the changes.

If you see fairseq file https://github.com/pytorch/fairseq/blob/master/examples/wav2vec/wav2vec_featurize.py there is .h5context extension is used by default for hdf5 files

**Comment by cyl250** [comment]
Hi, @maltium 
I am able to build wav2letter successfully and run the train steps on WSJ with the same train parameters.
And I have gotten a 1.57 loss in train set and 10.9 loss in dev set.
Compared to FBANK, 0.57 loss in train set and 2.68 loss in dev set.
I wounder whether you have met this problem.
Is there some suggestions ?
