### ISSUE TITLE
out of memory when using sota 2019 librispeech TDS CTC recipe

### ISSUE THREAD

**Issue by abramovi** [facebookresearch/wav2letter#616]
Hi, 

I am using 4 v100 gpu machine. I am running sota 2019 librispeech TDS CTC recipe on my **own data** and I am using **latest** w2l cuda docker.

batch size in cnfg file is 4 [https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/sota/2019/librispeech/train_am_tds_ctc.cfg](url).

I am getting the following error after the first epoch:

> 0417 00:06:50.763639  1292 Train.cpp:564] Epoch 2 started!
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Device out of memory:101):
In function virtual void* cuda::Allocator::nativeAlloc(size_t)
In file src/backend/cuda/memory.cpp:152
CUDA Error (2): out of memory

while running my gpus are at most in 40% usage.

any suggestion how how to increase the usage of the gpu and decrease the memory usage?

**Comment by lunixbochs** [comment]
Try the streaming convnet architecture, with transfer learning from the librivox model if you can. It's significantly easier to train than the transformer models and still quite accurate.

**Comment by vuongvantinh** [comment]
I have encountered some problems during training model. 
Below figure is training config, i prepared necerssary files and replaced old paths with appropriate paths 

![Capture2](https://user-images.githubusercontent.com/42363044/79859842-d7df7f80-83fb-11ea-88f0-cc83fffda81d.PNG)
After that i run 
`~/wav2letter/build_tools/Train train --flagsfile train_am_500ms_future_context.cfg --minloglevel=0 --logtostderr=1`
And got below result
![Capture](https://user-images.githubusercontent.com/42363044/79860823-9059f300-83fd-11ea-904e-a3465a515f97.PNG)
It seems model wasn't trained, each epochs start trainning afterwards ending immediately. I check `rundir `, there is no output model. I guess there is the issues with training config. Could you give me any suggestion? @lunixbochs

**Comment by abramovi** [comment]
> Try the streaming convnet architecture, with transfer learning from the librivox model if you can. It's significantly easier to train than the transformer models and still quite accurate.

@lunixbochs do you mean this config file https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/sota/2019/librivox/train_am_resnet_ctc.cfg ?

**Comment by tlikhomanenko** [comment]
@vuongvantinh, can you post your full log? It looks like all samples were filtered and no one is used for training.

**Comment by vuongvantinh** [comment]
@tlikhomanenko there is nothing in log file
below is perf file

`# date	time	epoch	nupdates	lr	lrcriterion	runtime	bch(ms)	smp(ms)	fwd(ms)	crit-fwd(ms)	bwd(ms)	optim(ms)	loss	train-TER	train-WER	/home/data/lists/dev-clean.lst-loss	/home/data/lists/dev-clean.lst-TER	/home/data/lists/dev-clean.lst-WER	avg-isz	avg-tsz	max-tsz	hrs	thrpt(sec/sec)`

and config file
```
{
    "config": [
        {
            "key": "runIdx",
            "value": "1"
        },
        {
            "key": "timestamp",
            "value": "2020-04-21, 2020-04-21"
        },
        {
            "key": "hostname",
            "value": "cd5c68d4b039"
        },
        {
            "key": "runPath",
            "value": "/home/data/inference_2019"
        },
        {
            "key": "username",
            "value": ""
        },
        {
            "key": "gflags",
            "value": "--flagfile=\n--fromenv=\n--tryfromenv=\n--undefok=\n--tab_completion_columns=80\n--tab_completion_word=\n--help=false\n--helpfull=false\n--helpmatch=\n--helpon=\n--helppackage=false\n--helpshort=false\n--helpxml=false\n--version=false\n--adambeta1=0.90000000000000002\n--adambeta2=0.999\n--am=\n--am_decoder_tr_dropout=0\n--am_decoder_tr_layerdrop=0\n--am_decoder_tr_layers=1\n--arch=am_500ms_future_context.arch\n--archdir=/home/data\n--attention=content\n--attentionthreshold=2147483647\n--attnWindow=no\n--attnconvchannel=0\n--attnconvkernel=0\n--attndim=0\n--batchsize=8\n--beamsize=2500\n--beamsizetoken=250000\n--beamthreshold=25\n--blobdata=false\n--channels=1\n--criterion=ctc\n--critoptim=sgd\n--datadir=\n--dataorder=input\n--decoderattnround=1\n--decoderdropout=0\n--decoderrnnlayer=1\n--decodertype=wrd\n--devwin=0\n--emission_dir=\n--emission_queue_size=3000\n--enable_distributed=true\n--encoderdim=0\n--eosscore=0\n--eostoken=false\n--everstoredb=false\n--fftcachesize=1\n--filterbanks=80\n--flagsfile=train_am_500ms_future_context.cfg\n--framesizems=25\n--framestridems=10\n--gamma=1\n--gumbeltemperature=1\n--input=flac\n--inputbinsize=100\n--inputfeeding=false\n--isbeamdump=false\n--iter=9223372036854775807\n--itersave=false\n--labelsmooth=0\n--leftWindowSize=50\n--lexicon=/home/data/am/librispeech-train+dev-unigram-10000-nbest10.lexicon\n--linlr=-1\n--linlrcrit=-1\n--linseg=0\n--lm=\n--lm_memory=5000\n--lm_vocab=\n--lmtype=kenlm\n--lmweight=0\n--localnrmlleftctx=300\n--localnrmlrightctx=0\n--logadd=false\n--lr=0.40000000000000002\n--lr_decay=9223372036854775807\n--lr_decay_step=9223372036854775807\n--lrcosine=false\n--lrcrit=0\n--maxdecoderoutputlen=200\n--maxgradnorm=0.5\n--maxisz=33000\n--maxload=-1\n--maxrate=10\n--maxsil=50\n--maxtsz=9223372036854775807\n--maxword=-1\n--melfloor=1\n--memstepsize=10485760\n--mfcc=false\n--mfcccoeffs=13\n--mfsc=true\n--minisz=200\n--minrate=3\n--minsil=0\n--mintsz=2\n--momentum=0\n--netoptim=sgd\n--noresample=false\n--nthread=1\n--nthread_decoder=1\n--nthread_decoder_am_forward=1\n--numattnhead=8\n--onorm=target\n--optimepsilon=1e-08\n--optimrho=0.90000000000000002\n--outputbinsize=5\n--pctteacherforcing=100\n--pcttraineval=1\n--pow=false\n--pretrainWindow=0\n--replabel=0\n--reportiters=1000\n--rightWindowSize=50\n--rndv_filepath=\n--rundir=/home/data\n--runname=inference_2019\n--samplerate=16000\n--sampletarget=0\n--samplingstrategy=rand\n--saug_fmaskf=27\n--saug_fmaskn=2\n--saug_start_update=-1\n--saug_tmaskn=2\n--saug_tmaskp=1\n--saug_tmaskt=100\n--sclite=\n--seed=0\n--show=false\n--showletters=false\n--silscore=0\n--smearing=none\n--smoothingtemperature=1\n--softwoffset=10\n--softwrate=5\n--softwstd=5\n--sqnorm=true\n--stepsize=9223372036854775807\n--surround=\n--tag=\n--target=tkn\n--test=\n--tokens=librispeech-train-all-unigram-10000.tokens\n--tokensdir=/home/data/am\n--train=/home/data/lists/train-clean-100.lst\n--trainWithWindow=false\n--transdiag=0\n--unkscore=-inf\n--use_memcache=false\n--use_saug=false\n--uselexicon=true\n--usewordpiece=true\n--valid=/home/data/lists/dev-clean.lst\n--warmup=8000\n--weightdecay=0\n--wordscore=0\n--wordseparator=_\n--world_rank=0\n--world_size=1\n--alsologtoemail=\n--alsologtostderr=false\n--colorlogtostderr=false\n--drop_log_memory=true\n--log_backtrace_at=\n--log_dir=\n--log_link=\n--log_prefix=true\n--logbuflevel=0\n--logbufsecs=30\n--logemaillevel=999\n--logfile_mode=436\n--logmailer=/bin/mail\n--logtostderr=true\n--max_log_size=1800\n--minloglevel=0\n--stderrthreshold=2\n--stop_logging_if_full_disk=false\n--symbolize_stacktrace=true\n--v=0\n--vmodule=\n"
        },
        {
            "key": "commandline",
            "value": "/root/wav2letter/build_tools/Train train --flagsfile train_am_500ms_future_context.cfg --minloglevel=0 --logtostderr=1"
        },
        {
            "key": "programname",
            "value": "/root/wav2letter/build_tools/Train"
        }
    ]
}
```
This problem happened to only streaming_convnets. I used the same data to train tds_ctc model in sota/2019 and it worked.

**Comment by vuongvantinh** [comment]
@tlikhomanenko You were right. All samples were filtered.
![Capture3](https://user-images.githubusercontent.com/42363044/80069882-48a5a980-856c-11ea-8397-12d79c731793.PNG)
But i don't know why all samples were filtered, this problem happened to only `streaming_convnets`. I used the same data to train `tds_ctc `model in sota/2019 and it worked well.

**Comment by vineelpratap** [comment]
When using multiple GPUs,  make sure you run train with distributed setting - https://github.com/facebookresearch/wav2letter/wiki/Distributed-training

**Comment by tlikhomanenko** [comment]
Closing due to inactivity. Feel free to reopen!
